### ISSUE TITLE
No drive working

### ISSUE THREAD

**Issue by wlpppaul** [skiselev/monster-fdc#2]
Hello,

i get "Drive not ready" on all drives i try to connect. I tried different cables with a 1.44MB and a 1.2MB Drive.
When accessing a: or b: the correct drive responds and lights up. But only two anounce drive not ready after some seconds.

I tried in a P2 and a 386sx.

Do you have and idea what could be the reason?

Thank you :-)

**Comment by skiselev** [comment]
A couple of things to check:
- Do you see the Multi-Floppy BIOS Extension messages/prompts when the system boots? If not, check that you have flashed that to the Flash ROM, and properly configured the ROM address
- Disable floppies in the system BIOS
- Disable the on board FDC if any (usually on P2 boards came with one)
- Of course, it could be a faulty FDC...  if nothing else helps, try swapping it with another FDC

BTW, I haven't tested Monster FDC on much newer systems (e.g. P2), and there might be some issues there...

**Comment by skiselev** [comment]
No response or reproducer. Closing the issue. Feel free to reopen if you have more information
