### ISSUE TITLE
Help diagnosing possible faulty controller

### ISSUE THREAD

**Issue by ImanolBarba** [skiselev/monster-fdc#9]
So I built a couple of these boards, and they both seem to have the same issue:

- Floppy BIOS runs, so that much is fine
- As soon as the floppy cable is inserted into the card, irregardless of the card being powered or inserted anywhere, the floppy drive light comes on and stays on. 
- OS detects floppies correctly as configured in the BIOS
- If I try to read from the drive it just does nothing and eventually the OS reports error
- I tried two different drives already, which I sourced from two different places

Could it be that the 82077aa controllers are bad or fake? I sourced all 4 of them from the same vendor.

I don't know how the controllers work, but it's weird the issue is present even when the card is not powered or grounded anywhere.

Any tips?

Thanks

**Comment by skiselev** [comment]
Really two options:
1. Floppy interface cable is reversed. Please make sure that the cable is connected properly. Pin 1 is marked on the FDC board. It also should be marked on floppy drives. Floppy cables normally have the first wire colored red or purple
2. The FDC IC is bad. Did you use FDC ICs from a reliable supplier?

**Comment by ImanolBarba** [comment]
Yeah my dumb ass was connecting the cable reversed on the drive, my bad.

Seems to work fine now, thanks for the help!
